default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
#  adapter: mysql2
#  encoding: utf8
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: root
#  password: toor
#  host: localhost

development:
  <<: *default
  database: db/development.sqlite3
#  database: bad_sns_development

test:
  <<: *default
  database: db/test.sqlite3
#  database: bad_sns_test

production:
  <<: *default
  database: db/production.sqlite3
#  database: bad_sns_production
